### ISSUE TITLE
Noisy notify when starting nvim

### ISSUE THREAD

**Issue by Jomik** [mistweaverco/kulala-cmp-graphql.nvim#1]
https://github.com/mistweaverco/kulala-cmp-graphql.nvim/blob/50fbc7c78eae013376fee78055c5b6a3e169bd40/lua/kulala-cmp-graphql/init.lua#L7
This seems a bit redundant 😄

**Comment by gorillamoe** [comment]
You're right, shame on me 😭 🙈.
